import './globals.css';
import type { Metadata } from 'next';
import AuthProvider from './Providers';

export const metadata: Metadata = {
  icons: '/favicon.svg',
  title: 'Car Rental App',
  description: 'Generated by CS673-Team6',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
